### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by erinking** [Samurai016/Minimal-Design#2]
This repository is included on the list of available open-source clock faces on https://github.com/Fitbit/ossapps but it does not appear to include an appropriate open-source `LICENSE` file accordingly. Would you please add one?
Other Fitbit projects on the ossapps list have chosen the MIT, GPL-3.0, or Unlicense License, so I suggest using one of those.

Read here to learn more:
https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository
https://choosealicense.com/

Best wishes

**Comment by Samurai016** [comment]
Thank you @erinking for letting me know, I just forgot it😂. 
I included the MIT license in the last [commit](../commit/2021efbadf454f841b2b7951c2df25ddbeba9195).
